# Numpy Basics

## Vetorial Structure

In [5]:
import numpy as np

In [6]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [7]:
[x * 2 for x in py_list]

[2, 4, 6, 8, 10]

In [ ]:
np_array * 2 # the 'same' output, but really faster

array([ 2,  4,  6,  8, 10])

In [11]:
np.array(1)

array(1)

In [12]:
np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.random.rand(2,3,4)

array([[[0.93413019, 0.5021122 , 0.31557284, 0.95394956],
        [0.71203821, 0.05042171, 0.74467245, 0.18802459],
        [0.28518887, 0.74747565, 0.12314506, 0.58616547]],

       [[0.77595594, 0.31775468, 0.97869374, 0.63275776],
        [0.30552005, 0.68069281, 0.50220206, 0.59700674],
        [0.34354656, 0.87059724, 0.85077801, 0.3517161 ]]])

some properties

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)      # número de dimensões (2)
print(arr.shape)     # formato (2 linhas, 3 colunas)
print(arr.size)      # total de elementos (6)
print(arr.dtype)     # tipo de dado (ex: int32, float64)
print(arr.itemsize)  # bytes por elemento

2
(2, 3)
6
int32
4


## Common array creation

In [18]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1, 10, 5) # 5 valores entre 1 e 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.eye(4) # matriz identidade 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2, 3)    # matriz 2x3, com valores aleatórios entre 0 e 1

array([[0.72941083, 0.78752357, 0.95453607],
       [0.2396824 , 0.4206183 , 0.98732321]])

## Vector operations

In [32]:
a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [33]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

In [34]:
a + b

array([11, 22, 33, 44])

In [35]:
a - b

array([ 9, 18, 27, 36])

In [36]:
a * b

array([ 10,  40,  90, 160])

In [37]:
a / b

array([10., 10., 10., 10.])

## Boardcasting

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b = np.array([10, 20, 30])
b

array([10, 20, 30])

In [46]:
a + b

array([[11, 22, 33],
       [14, 25, 36]])

## Indexing

In [48]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [50]:
arr[0, 1]

20

In [52]:
arr[:, 1]

array([20, 50, 80])

In [53]:
arr[1:, 1:]

array([[50, 60],
       [80, 90]])